#!/usr/bin/env zsh


# This file is part of mydot.

# mydot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.

# mydot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with mydot.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2020-2021, Maciej Barć <xgqt@riseup.net>
# Licensed under the GNU GPL v3 License

#      _             _
#  ___| | ___   __ _(_)_ __
# |_  / |/ _ \ / _` | | '_ \
#  / /| | (_) | (_| | | | | |
# /___|_|\___/ \__, |_|_| |_|
#              |___/

# shellcheck disable=1090


# ZDOTDIR Warning
[ ! -d "${ZDOTDIR}" ] && echo "!!!Warning!!! No ${ZDOTDIR} found!!!"

# Create ZSH cache directory
[ ! -d "${ZCACHEDIR}" ] && mkdir -p "${ZCACHEDIR}"

# Choose a theme if it's not set
if [ ! -e "${ZDOTDIR}/tty.zsh-theme" ] || [ ! -e "${ZDOTDIR}/emu.zsh-theme" ]
then
    echo "Choose which ZSH themes to use"
    zsh "${ZDOTDIR}/zsh-choose-theme.sh"
    source "${ZDOTDIR}/.zshrc"
fi

# Link one of greeters from
# greeters to zsh-greeter
if [ ! -e "${ZDOTDIR}/zsh-greeter" ]
then
    echo "Choose which ZSH greeter to use"
    zsh "${ZDOTDIR}/zsh-choose-greeter.sh"
else
    source "${ZDOTDIR}/zsh-greeter"
fi
