#!/bin/sh


#       _       _ _
# __  _(_)_ __ (_) |_ _ __ ___
# \ \/ / | '_ \| | __| '__/ __|
#  >  <| | | | | | |_| | | (__
# /_/\_\_|_| |_|_|\__|_|  \___|

# shellcheck disable=1090

# Usage:
# $ startx ~/.xinitrc [session]


# Autochoose a available session if none is given

cmdex() {
    if command -v "${1}" >/dev/null 2>&1
    then
	return 0
    else
	return 1
    fi
}

if [ -n "${1}" ]
then
    session="${1}"
else
    if cmdex gnome-session
    then
	session="gnome"
    elif cmdex startxfce4
    then
	session="xfce"
    elif cmdex mate-session
    then
	session="mate"
    elif cmdex startplasma-x11
    then
	session="kde"
    elif cmdex
    then
	session="lxqt"
    elif cmdex openbox
    then
	session="openbox"
    elif cmdex bspwm
    then
	session="bspwm"
    elif cmdex dwm
    then
	session="dwm"
    elif cmdex emacs
    then
	session="exwm"
    fi
fi


# Source files

# Xprofile
[ -f "${HOME}/.xprofile" ] && . ~/.xprofile
[ -f "${HOME}/.config/X11/xprofile" ] && . ~/.config/X11/xprofile

# Additional X scripts
# ex.: xrandr settings or session choice
[ -f "${HOME}/.xscripts" ] && . ~/.xscripts


# Start the session
case ${session} in
    bsp | bspwm )
	exec bspwm
	;;
    exwm | EXWM )
	exec emacs --load ~/.emacs.d/exwm-config.el
	;;
    gnome )
	exec gnome-session
	;;
    lxqt | LXQt )
	exec startlxqt
	;;
    kde )
	exec startplasma-x11
	;;
    mate )
	exec mate-session
	;;
    xfce | xfce4 )
	exec startxfce4
	;;
    # Anything different is run as command
    * )
	exec "${1}"
	;;
esac
