#!/bin/sh


# Copyright (c) 2020, XGQT
# Licensed under the ISC License

#       _       _ _
# __  _(_)_ __ (_) |_ _ __ ___
# \ \/ / | '_ \| | __| '__/ __|
#  >  <| | | | | | |_| | | (__
# /_/\_\_|_| |_|_|\__|_|  \___|

# shellcheck disable=1090

# Usage:
# $ startx ~/.xinitrc [session]


command_exists() {
    if command -v "${1}" >/dev/null 2>&1
    then
        return 0
    else
        return 1
    fi
}

source_file () {
    [ -f "${1}" ] && . "${1}"
}


if [ -n "${1}" ]
then
    session="${1}"
    if ! command_exists "${1}"
    then
        echo "WARNING: Command ${1} does not exist"
        echo "WARNING: This may get overwritten by files sourced later"
    fi
else
    # Autochoose a available session if none is given
    # This works because in last 'case'
    # we execute the raw command (not a keyword)
    echo "WARNING: No session chosen"
    echo "WARNING: Chosing one from a predefined set"
    echo "WARNING: This may get overwritten by files sourced later"
    for s in \
        bspwm \
        dwm \
        enlightenment_start \
        gnome-session \
        lxqt-session \
        mate-session \
        openbox \
        startplasma-x11 \
        startxfce4
    do
        if command_exists "${s}"
        then
            session="${s}"
            break
        fi
    done
    unset s
fi


# Source files

# Xprofile
source_file "${HOME}/.xprofile"
source_file "${HOME}/.config/X11/xprofile"

# Additional X scripts
# ex.: xrandr settings or session choice
source_file "${HOME}/.xscripts"


# Start the session
# 'case' is for ease of executing startx from the console
case ${session} in
    bsp | bspwm )
        exec bspwm
        ;;
    E | e | enlightenment )
        exec enlightenment_start
        ;;
    exwm | EXWM )
        exec emacs --load "${HOME}/.emacs.d/exwm-config.el"
        ;;
    gnome )
        exec gnome-session
        ;;
    lxqt | LXQt )
        exec startlxqt
        ;;
    kde )
        exec startplasma-x11
        ;;
    mate )
        exec mate-session
        ;;
    xfce | xfce4 )
        exec startxfce4
        ;;
    # Anything different is run as command
    * )
        if command_exists "${session}"
        then
            exec "${session}"
        else
            echo "ERROR: Command ${session} does not exist"
        fi
        ;;
esac
