#!/bin/sh


# Copyright (c) 2020, XGQT
# Licensed under the ISC License

# shellcheck disable=1090


# Run system's xinitrc.d scripts

if [ -d /etc/X11/xinit/xinitrc.d ]; then
    for f in /etc/X11/xinit/xinitrc.d/?*; do
        [ -x "${f}" ] && . "${f}"
    done
    unset f
fi

# Keyboard

# Polish + holding Caps Lock acts as Control
if command -v setxkbmap >/dev/null 2>&1; then
    setxkbmap pl -option "caps:ctrl_modifier" &
fi

# Use Caps Lock as Escape
if command -v xcape >/dev/null 2>&1; then
    xcape -e "Caps_Lock=Escape" &
fi


# Xset

if command -v xset >/dev/null 2>&1; then

    # disable beeping
    xset b off

    # screensaver timeout
    xset s 1200 0
fi


# Qt in GTK desktops

# Detect qt5ct
if command -v qt5ct >/dev/null 2>&1; then
    QT_QPA_PLATFORMTHEME="qt5ct"
    export QT_QPA_PLATFORMTHEME
fi
