---


# This file is part of mydot.

# mydot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# mydot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with mydot.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2020-2021, Maciej Barć <xgqt@protonmail.com>
# Licensed under the GNU GPL v3 License


image: gentoo/stage3-amd64:latest


variables:
   FEATURES: "getbinpkg"
   GIT_SUBMODULE_STRATEGY: recursive
   MAKEOPTS: "--jobs=10"
   PORTAGE_BINHOST: "https://xgqt.gitlab.io/gentoo-mini-mirror/binpkgs"
   TERM: "dumb"
   USE: "-perl"


stages:
  - shcheck
  - install


before_script:
  - mkdir -p /var/cache/distfiles
  - mkdir -p /var/db/repos/gentoo
  - time emerge-webrsync


shcheck:
  stage: shcheck
  script:
    - emerge -1nq "dev-util/shellcheck-bin"
    - make test

install:
  stage: install
  script:
    - emerge -1nq "dev-vcs/git"
    - make install
