---


# This file is part of mydot.

# mydot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# mydot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with mydot.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2020-2021, Maciej Barć <xgqt@protonmail.com>
# Licensed under the GNU GPL v3 License


image: alpine:latest


variables:
   GIT_SUBMODULE_STRATEGY: "recursive"
   TERM: "dumb"


stages:
  - test
  - install


before_script:
  - apk update
  - apk add make


# Emacs - Alpine
# Test the loading of Emacs configuration files.

emacs:
  stage: test

  script:
    - apk add emacs
    - make test-emacs

  rules:
    - changes:
        - emacs/.config/emacs/*


# Guile - Alpine
# Test the loading of Guile configuration files.
# TODO: Maybe use a GuixSD image?

guile:
  stage: test

  script:
    - apk add guile
    - make test-guile


# Shellcheck - Alpine
# Check shell scripts with 'shellcheck'.

shellcheck:
  stage: test

  script:
    - apk add shellcheck
    - make test-shellcheck


# Bootstrap - Alpine
# This stage is primarily for checking if the 'bootstrap.sh'
# script works. We do not use curl here (as README suggests)
# because the repository where the script is may change.

bootstrap:
  stage: install
  needs: ["shellcheck"]

  script:
    - apk add git ncurses stow
    - sh ./.helpers/bootstrap.sh


# Make-Install - Gentoo
# We test if we can run 'make install' on default Gentoo
# image (made from stage3).
# We do not install 'stow' - 'pystow' will be automatically
# installed by 'install_pystow.sh' script that is executed
# by the 'Makefile' (when no other 'stow' implementation
# is available).
# We do not install git because we already have the
# repository initialized (by the GitLab CI) and we can
# use the preinstalled 'wget' to install pystow.

make-install:
  image: gentoo/stage3-amd64:latest
  stage: install
  needs: ["shellcheck"]

  before_script:
    - export PATH="${PATH}:${HOME}/.local/bin"
    - make dependencies

  script:
    - make install
