#!/bin/sh


#      _
#  ___| |_ _____      __
# / __| __/ _ \ \ /\ / /
# \__ \ || (_) \ V  V /
# |___/\__\___/ \_/\_/
#     __ _ _
#    / _(_) | ___  ___
#   | |_| | |/ _ \/ __|
#  _|  _| | |  __/\__ \
# (_)_| |_|_|\___||___/


msg() {
    echo "$(tput bold)${1}$(tput sgr0)"
}

err_msg() {
    msg "${1}"
    exit 1
}

exists() {
    if command -v "${1}" >/dev/null 2>&1
    then
        return 0
    else
        return 1
    fi
}


# >>> Needed checks

# check for stow
if exists stow
then
    stow_impl=stow
elif exists xstow
then
    stow_impl=xstow
else
    err_msg "There is no stow on the sytem! Exiting"
fi

# check needed directories
for chkdir in "${HOME}/.config" "${HOME}/.local/share" \
		                        "${HOME}/.emacs.d" \
		                        "${HOME}/.config/mpd/playlists"
do
    if [ -e "${chkdir}" ]
    then
        echo "${chkdir} exists, good"
    else
	    mkdir -p "${chkdir}"
	    echo "${chkdir} created"
    fi
done


# >>> Perform desired Stow action

# then we iterate through everything there
for target in *
do
    # check if it's a directory
    if [ -d "${target}" ]
    then
	    # finally do some work
	    if [ "${1}" = "remove" ]
        then
            msg "Removing $(tput bold)$target$(tput sgr0)"
	        ${stow_impl} -v -t "${HOME}" -D "${target}"
	    else
            msg "Installing $(tput bold)$target$(tput sgr0)"
	        ${stow_impl} -v -t "${HOME}" "${target}"
	    fi
    fi
done
