#!/bin/sh


# Copyright (c) 2020, XGQT
# Licensed under the ISC License

# "Aggresively" update mydot


# Go to mydot source
cd "$(dirname "${0}")" || err_msg "Can't cd into $(basename "${0}")"

if sh stowdot remove
then
    git reset --hard
    git pull
    sh stowdot
fi

echo "mydot updated"
