#!/bin/sh


# Copyright (c) 2020, XGQT
# Licensed under the ISC License

# "Aggresively" update mydot


if sh stowdot remove
then
    git reset --hard
    git pull
    sh stowdot
fi

echo "mydot updated"
