#!/bin/sh


# This file is part of mydot.

# mydot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.

# mydot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with mydot.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2020-2021, Maciej Barć <xgqt@riseup.net>
# Licensed under the GNU GPL v3 License

# shellcheck disable=1090,1091

# Usage:
# $ startx ~/.config/X11/xinitrc [session]


command_exists() {
    if command -v "${1}" >/dev/null 2>&1
    then
        return 0
    else
        return 1
    fi
}

source_file () {
    [ -f "${1}" ] && . "${1}"
}


if [ -n "${1}" ]
then
    session="${1}"
else
    # Autochoose a available session if none is given
    # This works because in last 'case'
    # we execute the raw command (not a keyword)
    echo "WARNING: No session chosen"
    echo "WARNING: Chosing one from a predefined set"
    echo "WARNING: This may get overwritten by files sourced later"
    for s in \
        bspwm \
        cinnamon-session \
        dwm \
        enlightenment_start \
        gnome-session \
        lxqt-session \
        mate-session \
        openbox \
        startplasma-x11 \
        startxfce4
    do
        if command_exists "${s}"
        then
            session="${s}"
            break
        fi
    done
    unset s
fi


# Source files

# Xprofile
source_file "${HOME}/.xprofile"
source_file "${HOME}/.config/X11/xprofile"

# Additional X scripts
# ie.: xrandr settings or session choice
source_file "${HOME}/.xscripts"


# Start the session
# 'case' is for ease of executing startx from the console
case "${session}"
in
    [Bb][Ss][Pp] | [Bb][Ss][Pp][Ww][Mm] )
        exec bspwm
        ;;
    [Cc][Ii][Nn][Nn][Aa][Mm][Oo][Nn] )
        exec cinnamon-session
        ;;
    E | e | [Ee][Nn][Ll][Ii][Gg][Hh][Tt][Ee][Nn][Mm][Ee][Nn][Tt] )
        exec enlightenment_start
        ;;
    [Ee][Xx][Ww][Mm] )
        exec emacs --load "${USER_EMACS_DIRECTORY}/exwm-config.el"
        ;;
    [Gg][Nn][Oo][Mm][Ee] )
        exec gnome-session
        ;;
    [Ll][Xx][Qq][Tt] )
        exec startlxqt
        ;;
    [Kk][Dd][Ee] | *[Pp][Ll][Aa][Ss][Mm][Aa]* )
        QT_QPA_PLATFORMTHEME=""
        export QT_QPA_PLATFORMTHEME
        exec startplasma-x11
        ;;
    [Mm][Aa][Tt][Ee] )
        exec mate-session
        ;;
    [Xx][Ff][Cc][Ee]* )
        exec startxfce4
        ;;
    # Anything different is run as command
    * )
        if command_exists "${session}"
        then
            exec "${session}"
        else
            echo "ERROR: Command ${session} does not exist"
        fi
        ;;
esac
