#!/bin/sh


#                                            .
#     .vir.                                 d$b
#  .d$$$$$$b.     .cd$$b.     .d$$b.   d$$$$$$$$$$$b  .d$$b.      .d$$b.
#  $$$$( )$$$b  d$$$()$$$.   d$$$$$$$b Q$$$$$$$P$$$P.$$$$$$$b.  .$$$$$$$b.
#  Q$$$$$$$$$$ d$$$$$$$$P"  d$$$PQ$$$$b.   $$$$.   .$$$P' `$$$ .$$$P' `$$$
#    "$$$$$$$P  Q$$$$$$$b  d$$$P   Q$$$$b  $$$$b   $$$$b..d$$$ $$$$b..d$$$
#   d$$$$$$P"    "$$$$$$$$ Q$$$     Q$$$$  $$$$$   `Q$$$$$$$P  `Q$$$$$$$P
#  $$$$$$$P        `"""""   ""        ""   Q$$$P     "Q$$$P"     "Q$$$P"
#  `Q$$P"                                   """

# My Aliases


# System specific

case $(uname)
in
    *Linux*)
        alias ls='ls --color=auto'
        alias ll='ls -lahF --color=always'
        alias grep='grep --colour=always'
        alias tree='tree -C -F'
        alias t='tree -a -L 2 -I ".git"'
        ;;
    *)
        alias ll='ls -lahF'
        alias tree='tree -F'
        alias t='tree -a -L 2'
        ;;
esac


# Authorization

alias rp='sudo '


# Editing

alias ,,='cd ../..'

alias e='emacs -nw'
alias n='nano'
alias v='vim'

alias nranger='EDITOR=nano ranger'
alias open='xdg-open'
alias rcp='rsync --stats --progress'

alias ed-shrc='${EDITOR} ${HOME}/.profile'
alias so-shrc='source ${HOME}/.profile'

alias clear-zhistory='cat /dev/null > ${ZCACHEDIR}/zhistory'
alias ed-bashrc='${EDITOR} ${HOME}/.bashrc'
alias so-bashrc='source ${HOME}/.bashrc'

alias clear-zhistory='cat /dev/null > ${ZCACHEDIR}/zhistory'
alias ed-bashrc='${EDITOR} ${ZDOTDIR}/.zshrc'
alias so-zshrc='source ${ZDOTDIR}/.zshrc'

alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'


# Git

alias Ga='git add .'
alias Gc='git commit'
alias Gd='git diff'
alias Gg='git pull'
alias Gl='git log --oneline --graph'
alias Go='git clone --recursive --verbose'
alias Gp='git push'
alias Gr='git reset --hard'
alias Gs='git status'


# Network

alias mtr='mtr --show-ips --curses'
alias seen='sudo watch arp-scan --localnet'
alias seeo='sudo netstat -acnptu'


# Portage

alias E='tail -f ${EPREFIX}/var/log/emerge.log'
alias F='tail -f ${EPREFIX}/var/log/emerge-fetch.log'
alias P='cd ${EPREFIX}/etc/portage && tree -a -L 2'

alias pep='sudo emerge -av'
alias chu='sudo emerge -avNUD @world'
alias ewup='sudo emerge -avuDNU --with-bdeps=y @world'
alias slr='sudo smart-live-rebuild'


# Other PKG managers

alias fpk='flatpak'


# youtube-dl

alias ytd='youtube-dl -i -o "%(title)s.%(ext)s"'

alias ytd-mp3='youtube-dl -i --extract-audio --audio-format mp3 -o "%(playlist_index)s - %(title)s.%(ext)s"'
alias ytd-webm='youtube-dl -i --format webm -o "%(title)s.%(ext)s"'

alias ytd-sub-en='youtube-dl -i --write-srt --sub-lang en -o "%(title)s.%(ext)s"'
alias ytd-sub-pl='youtube-dl -i --write-srt --sub-lang pl -o "%(title)s.%(ext)s"'
