#!/bin/sh


#                                            .
#     .vir.                                 d$b
#  .d$$$$$$b.     .cd$$b.     .d$$b.   d$$$$$$$$$$$b  .d$$b.      .d$$b.
#  $$$$( )$$$b  d$$$()$$$.   d$$$$$$$b Q$$$$$$$P$$$P.$$$$$$$b.  .$$$$$$$b.
#  Q$$$$$$$$$$ d$$$$$$$$P"  d$$$PQ$$$$b.   $$$$.   .$$$P' `$$$ .$$$P' `$$$
#    "$$$$$$$P  Q$$$$$$$b  d$$$P   Q$$$$b  $$$$b   $$$$b..d$$$ $$$$b..d$$$
#   d$$$$$$P"    "$$$$$$$$ Q$$$     Q$$$$  $$$$$   `Q$$$$$$$P  `Q$$$$$$$P
#  $$$$$$$P        `"""""   ""        ""   Q$$$P     "Q$$$P"     "Q$$$P"
#  `Q$$P"                                   """

# My Aliases


# System specific

case $(uname)
in
    *Linux*)
        alias ls='ls --color=auto'
        alias ll='ls -lahF --color=always'
        alias grep='grep --colour=always'
        alias tree='tree -C -F'
        alias t='tree -a -L 2 -I ".git"'
        ;;
    *)
        alias ll='ls -lahF'
        alias tree='tree -F'
        alias t='tree -a -L 2'
        ;;
esac


# Authorization

alias rp='sudo '


# Editing

alias ,,='cd ../..'

alias e='emacs -nw'
alias n='nano'
alias v='vim'

alias hl='highlight -O truecolor'

alias nuke='rm -rfd'

alias nranger='EDITOR=nano ranger'
alias open='xdg-open'
alias rcp='rsync --stats --progress'

alias ed-shrc='${EDITOR} ${HOME}/.profile'
alias so-shrc='source ${HOME}/.profile'

alias clear-zhistory='cat /dev/null > ${ZCACHEDIR}/zhistory'
alias ed-bashrc='${EDITOR} ${HOME}/.bashrc'
alias so-bashrc='source ${HOME}/.bashrc'

alias clear-zhistory='cat /dev/null > ${ZCACHEDIR}/zhistory'
alias ed-zshrc='${EDITOR} ${ZDOTDIR}/.zshrc'
alias so-zshrc='source ${ZDOTDIR}/.zshrc'

alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'


# Git

alias Ga='git add .'
alias Gc='git commit'
alias Gd='git diff'
alias Gg='git pull'
alias Gl='git log --oneline --graph'
alias Go='git clone --recursive --verbose'
alias Gp='git push'
alias Gr='git reset --hard'
alias Gs='git status'


# Network

alias mtr='mtr --show-ips --curses'
alias seen='sudo watch arp-scan --localnet'
alias seeo='sudo netstat -acnptu'


# Portage

alias E='tail -f ${EPREFIX}/var/log/emerge.log'
alias F='tail -f ${EPREFIX}/var/log/emerge-fetch.log'
alias P='cd ${EPREFIX}/etc/portage && tree -a -L 2'

alias pep='sudo emerge -av'
alias chu='sudo emerge -avNUD @world'
alias ewup='sudo emerge -avuDNU --with-bdeps=y @world'
alias slr='sudo smart-live-rebuild'


# Other PKG managers

alias fpk='flatpak'


# youtube-dl

alias ytd='youtube-dl -i -o "%(title)s.%(ext)s"'

alias ytd-bestaudio='youtube-dl -i -f bestaudio -x -o "%(playlist_index)s - %(title)s.%(ext)s"'
alias ytd-flac='youtube-dl -i -f bestaudio -x --audio-format flac -o "%(playlist_index)s - %(title)s.%(ext)s"'
alias ytd-mp3='youtube-dl -i -f bestaudio -x --audio-format mp3 -o "%(playlist_index)s - %(title)s.%(ext)s"'
alias ytd-opus='youtube-dl -i -f bestaudio -x --audio-format opus -o "%(playlist_index)s - %(title)s.%(ext)s"'
alias ytd-webm='youtube-dl -i --format webm -o "%(title)s.%(ext)s"'

alias ytd-sub-en='youtube-dl -i --write-srt --sub-lang en -o "%(title)s.%(ext)s"'
alias ytd-sub-pl='youtube-dl -i --write-srt --sub-lang pl -o "%(title)s.%(ext)s"'


# CD aliases
# If "functions" can be sourced
# shellcheck disable=SC1090
if . "${HOME}/.config/sh/functions" >/dev/null 2>&1
then
    # compatibility
    cd_alias mydot "${HOME}"/mydot
    # system
    cd_alias conf /etc/conf.d
    cd_alias gentoo-tree /var/db/repos/gentoo
    cd_alias linux-src /usr/src/linux
    cd_alias localht /var/www/localhost/htdocs
    cd_alias logs /var/log
    cd_alias services /etc/init.d
    cd_alias tmp /tmp
    cd_alias www /var/www
    # user - standard
    cd_alias data "${HOME}"/Data
    cd_alias desktop "${HOME}"/Desktop
    cd_alias diary "${HOME}"/Documents/Diary
    cd_alias documents "${HOME}"/Documents
    cd_alias downloads "${HOME}"/Downloads
    cd_alias games "${HOME}"/Games
    cd_alias music "${HOME}"/Music
    cd_alias pictures "${HOME}"/Pictures
    cd_alias programming "${HOME}"/Documents/Programming
    cd_alias videos "${HOME}"/Videos
    # user - git
    cd_alias eternal "${HOME}"/Git/eternal
    cd_alias gentoo-dev "${HOME}"/Git/gentoo
    cd_alias guru "${HOME}"/Git/gentoo/guru
    cd_alias mine "${HOME}"/Git/mine
    cd_alias mydot "${HOME}"/Git/mine/mydot
    cd_alias other "${HOME}"/Git/other
    cd_alias pre "${HOME}"/Git/pre
    cd_alias src_ "${HOME}"/Git/src_prepare
    cd_alias src_overlay "${HOME}"/Git/src_prepare/src_prepare-overlay
    # user - hidden
    cd_alias applications "${HOME}"/.local/share/applications
    cd_alias apps "${HOME}"/.local/share/applications
    cd_alias autostart "${HOME}"/.config/autostart
    cd_alias bins "${HOME}"/.bin
    cd_alias config "${HOME}"/.config
    cd_alias zcachedir "${ZCACHEDIR}"
    cd_alias zdotdir "${ZDOTDIR}"
fi
