#!/bin/sh


# POSIX-compatible shell functons


# Check if 1st string contains the 2nd
contains_string() {
    string="${1}"
    substring="${2}"

    if [ "${string#*${substring}}" != "${string}" ]
    then
        # $substring is in $string
        return 0
    else
        # $substring is not in $string
        return 1
    fi
}


# Source a file if it exists
source_file() {
    [ -f "${1}" ] && . "${1}"
}


# This function first checks if specified directory
# already is in path, if it is not and it exists
# it is added to the path
add_to_path() {
    if ! contains_string "${PATH}" "${1}"
    then
        if [ -d "${1}" ]
        then
            export PATH=${PATH}:${1}
        fi
    fi
}


# Add some dirs

setup_path() {
    add_to_path /bin
    add_to_path /opt/bin
    add_to_path /sbin
    add_to_path /usr/bin
    add_to_path /usr/local/bin
    add_to_path /usr/local/sbin
    add_to_path /usr/sbin

    # User's programs
    add_to_path "${HOME}/.bin"
    add_to_path "${HOME}/.local/share/bin"

    # Cabal (Haskell)
    add_to_path "${HOME}/.cabal/bin"

    # Cargo (Rust)
    add_to_path "${HOME}/.cargo/bin"

    # GO
    add_to_path "${HOME}/go/bin"

    # Node
    add_to_path "${HOME}/.npm/bin"

    # Python
    add_to_path "${HOME}/.local/bin"
}

mkcd() {
    mkdir "${1}" && cd "${1}"
}
