#!/bin/sh


# This file is part of mydot.

# mydot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# mydot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with mydot.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2020, XGQT
# Licensed under the GNU GPL v3 License

# shellcheck disable=2016


if [ -z "${TERMINAL}" ]
then
    for t in \
        alacritty \
        aterm \
        gnome-terminal \
        kitty \
        konsole \
        mate-terminal \
        roxterm \
        sakura \
        st \
        terminator \
        terminology \
        tilix \
        urxvt \
        xfce4-terminal \
        xst \
        xterm
    do
        if command_exists "${t}"
        then
            TERMINAL="${t}"
            break
        fi
    done
    unset t
fi

a_k_a terminal '${TERMINAL}'
