#!/usr/bin/env zsh


#          _
#  _______| |__  _ __ ___
# |_  / __| '_ \| '__/ __|
#  / /\__ \ | | | | | (__
# /___|___/_| |_|_|  \___|


# ZSH path

# User's programs
export PATH=$PATH:$HOME/.bin
export PATH=$PATH:$HOME/.local/share/bin

# Python
export PATH=$PATH:$HOME/.local/bin

# GO
export PATH=$PATH:$HOME/go/bin

# Node
export PATH=$PATH:$HOME/.npm/bin


# Completion

# Extendedglob
setopt extendedglob

# Load compinit
autoload -U compinit
compinit -d $ZCACHEDIR/zcompdump

# Advanced tab-completion
zstyle ':completion:*:descriptions' format '%U%B%d%b%u'
zstyle ':completion:*:warnings' format '%BSorry, no matches for: %d%b'
zstyle ':completion:*' menu select

# Correction
setopt correctall


# History

# Necessary to save history
HISTFILE=$ZCACHEDIR/zhistory
HISTSIZE=5000
SAVEHIST=$HISTSIZE

# Ignore duplicates
setopt hist_ignore_all_dups

# Ignore space
setopt hist_ignore_space

# Save immediatelly, share history between terminals
setopt share_history


# Key bindings

# Kill & Yank
# for this set Emacs key bindings
bindkey -e

# Ctrl-left and Ctrl-right
bindkey "^[[1;5D" backward-word
bindkey "^[[1;5C" forward-word

# Del, Home and End
bindkey "^[[3~" delete-char
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

# Reverse search
bindkey "^R" history-incremental-search-backward

# Remove C-d binding (list-choices/delete-char-or-list)
bindkey -r "^D"


# Aliases

# Source shell-agnostic aliases
source $ZDOTDIR/aliases


# Theme

# Prompt init
autoload -U promptinit
promptinit

# Set themes
ztheme_tty="$ZDOTDIR/tty.zsh-theme"
ztheme_emu="$ZDOTDIR/emu.zsh-theme"

# Source appropriate theme
if [ -z $DISPLAY ]; then
    # theme in tty
    [ -f $ztheme_tty ] && source $ztheme_tty
else
    # theme in emulators
    [ -f $ztheme_emu ] && source $ztheme_emu
fi


# Plugins

# Syntax coloring
zplug_sh="$ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
[ -f $zplug_sh ] && source $zplug_sh

# Autosuggestions
zplug_as="$ZDOTDIR/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh"
[ -f $zplug_as ] && source $zplug_as

# Autosuggestions highlight style
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=6"

# Check Git branch
git_check () {
    branch=$(git branch 2>/dev/null | sed -n -e 's/^\* \(.*\)/\1/p')
    [ ! -z $branch ] && echo "$pre_git_check$branch$post_git_check"
}


# GPG

# Export some vars
export GPG_TTY=$(tty)
export PINENTRY_USER_DATA="USE_CURSES=1"

# Start GPG agent
if command -v gpg-agent >/dev/null 2>&1; then
    pidof gpg-agent &>/dev/null || gpg-agent --daemon 2>/dev/null
fi


# Miscellaneous

# Prompt Substring
# used by git_check
setopt PROMPT_SUBST

# Color
use_color=true

# Directory name to change dir
setopt autocd

# Do not beep
unsetopt beep

# Command Editor
autoload -U edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

case $TERM in
    xterm* )
	# Change the window title of X terminals
        precmd () { print -Pn "\e]0;${USER}@${HOST}:${PWD/#$HOME/\~}\a"; } ;;
    dumb )
	# For some SSH sessions (Emacs)
	unsetopt zle
	unsetopt prompt_cr
	unsetopt prompt_subst
	unfunction precmd
	unfunction preexec
	PS1='$ '
esac

# ls after changing directory
chpwd() ls
