#!/usr/bin/env python3


"""
This file is part of mydot.

mydot is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

mydot is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with mydot.  If not, see <https://www.gnu.org/licenses/>.

Copyright (c) 2020, XGQT
Licensed under the GNU GPL v3 License

CRON example:
0  *  *  *  *  python3 /home/user/.local/share/cron/logrot /home/user/.cache/cron/*.log
"""


import argparse
import gzip
import os


parser = argparse.ArgumentParser(
    description="Log file rotate script (meant to be run using cron)",
    epilog="Copyright (c) 2020, XGQT (License: GNU GPL v3)"
)
parser.add_argument(
    "-o", "--out",
    type=str,
    help="the directory to rotate to"
)
parser.add_argument(
    "-s", "--size",
    type=float, default=1,
    help="minimal size to rotate (in MB)"
)
parser.add_argument(
    "-k", "--keep",
    action="store_true",
    help="don't remove the files"
)
parser.add_argument(
    "files",
    type=str, nargs="+"
)
args = parser.parse_args()


def main():

    for f in args.files:
        if os.path.isfile(f):

            mb = os.path.getsize(f) / 1048576
            if mb >= args.size:

                if args.out:
                    ad = args.out
                else:
                    ad = os.path.dirname(f)

                an = os.path.basename(f)
                b = bytearray(open(f, "rb").read())
                with gzip.open(os.path.join(ad, an + ".gz"), "wb") as a:
                    a.write(b)

                if not args.keep:
                    try:
                        os.remove(f)
                    except Exception:
                        pass


if __name__ == "__main__":
    main()
