#!/bin/sh


trap 'exit 128' INT
export PATH


prog_name=$(basename "${0}")
log_dir="${HOME}/.cache/cron"
log_file="${log_dir}/${prog_name}.log"


run_command() {
    if ! "${@}" 2>&1
    then
        echo "ERROR: ${*} failed!"
        exit 1
    fi
}


mkdir -p "${log_dir}" >/dev/null 2>&1


(
    run_command echo ">>> Disk"
    run_command df
    run_command echo ">>> Memory"
    run_command free
    run_command echo ">>> Sensors"
    run_command sensors
) | busybox ts '[%Y-%m-%d %H:%M:%S]' >> "${log_file}" 2>&1
