#!/bin/sh

#  _
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_| 

### Workspaces
#
# Spawn 10 desktops on each monitor
bspc query -M | while read -r monitor
	do bspc monitor "$monitor" -d 1 2 3 4 5 6 7 8 9 0
done

### Main Config
#
bspc config border_width		3
bspc config window_gap			12
#
bspc config split_ratio			0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		true
#
bspc config focus_follows_pointer	true
#
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true
#
bspc config normal_border_color		"#362842"
bspc config active_border_color		"#743e5e"
bspc config focused_border_color	"#743e5e"
bspc config urgent_border_color		"#e87884"
bspc config presel_border_color		"#8e4b73"
bspc config presel_feedback_color	"#8e4b73"

### Rules
#
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Emacs state=tiled
bspc rule -a "Tor Browser" state=floating

### Set up bspwm session
#
# Start some programs
sxhkd &
mpd &
compton -b &
tint2 &
# feh: first run
#      feh --bg-scale /path/to/image.file
~/.fehbg &
dunst &
nm-applet &
pasystray &
xfce4-power-manager
xset b off
xset s 1200 0
xss-lock -- i3lock -c 000000 &
#
# GNOME Terminal + tmux
bspc desktop -f 1
bspc desktop -l monocle
gnome-terminal -- tmux new-session -s main
sleep 1
#
# Welcome
bspc desktop -f 2
notify-send "Welcome" "Have a great day"
sleep 1
