#!/bin/sh


# This file is part of mydot.

# mydot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.

# mydot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with mydot.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2020-2021, Maciej Barć <xgqt@riseup.net>
# Licensed under the GNU GPL v3 License

# shellcheck disable=1117


trap 'exit 128' INT
export PATH


prog_name="$(basename "${0}")"

log_dir="${HOME}/.cache/cron"
log_file="${prog_name}.log"

prog_desc="simple script to be used with cron"
prog_args=""


usage() {
    cat << USAGE
Usage: ${prog_name} [OPTION] ${prog_args}
${prog_name} - ${prog_desc}

Options:
    -V,      --version        show program version
    -d DIR,  --log-dir DIR    specify the log directory
    -f FILE, --log-file FILE  specify the log file
    -h,      --help           show avalible options

Copyright (c) 2020-2021, Maciej Barć <xgqt@riseup.net>
Licensed under the GNU GPL v3 License
USAGE
}

version() {
    cat <<EOF
${prog_name} 9999

Copyright (c) 2020-2021, Maciej Barć <xgqt@riseup.net>
Licensed under the GNU GPL v3 License
EOF
}

run_command() {
    echo "[C] Command: ${1^}"
    echo "[R] Running: ${*}"
    if eval "${@}" 2>&1
    then
        echo "[S] Success: ${*}"
        return 0
    else
        echo "[F] Failed: ${*}"
        return 1
    fi
}

log_command() {
    run_command "${@}" | busybox ts '[%Y-%m-%d %H:%M:%S]' >> "${log_dir}/${log_file}" 2>&1
}


while [ -n "${1}" ]
do
    case "${1}"
    in
        -h | -help | --help )
            usage
            exit 0
            ;;
        -V | -version | --version )
            version
            exit 0
            ;;
        -d | --log-dir )
            log_dir="${2}"
            ;;
        -f | --log-file )
            log_file="${2}"
            ;;
        -* )
            version
            echo
            usage
            exit 1
            ;;
    esac
    shift
done

if [ -z "${log_dir}" ] || [ -z "${log_file}" ]
then
    exit 1
fi

mkdir -p "${log_dir}" >/dev/null 2>&1 || exit 1


log_command eix-sync ">/dev/null"
log_command eix-update ">/dev/null"
log_command emerge --usepkg-exclude "\*" -Duvp @world
log_command emerge --usepkg-exclude "\*" -Dfu @world ">/dev/null"
