---


# This file is part of mydot.

# mydot is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# mydot is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with mydot.  If not, see <https://www.gnu.org/licenses/>.

# Copyright (c) 2021, Maciej Barć <xgqt@riseup.net>
# Licensed under the GNU GPL v3 License


name: CI
on: [push, pull_request]


jobs:


  test-emacs:
    name: "Test-Emacs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install dependencies"
        run: |
          sudo apt-get install -y make emacs

      - name: "Run tests"
        run: |
          make test-emacs


  test-guile:
    name: "Test-Guile"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install dependencies"
        run: |
          sudo apt-get install -y make guile-3.0

      - name: "Run tests"
        run: |
          make test-guile


  test-racket:
    name: "Test-Racket"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install dependencies"
        run: |
          sudo apt-get install -y make racket

      - name: "Run tests"
        run: |
          make test-racket


  test-shellcheck:
    name: "Test-Shellcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install dependencies"
        run: |
          sudo apt-get install -y make shellcheck

      - name: "Run tests"
        run: |
          make test-shellcheck


  bootstrap:
    name: "Bootstrap"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install dependencies"
        run: |
          sudo apt-get install -y make git stow

      - name: "Run tests"
        env:
          TERM: "dumb"
        run: |
          sh ./scripts/bootstrap.sh


  install:
    name: "Install"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install dependencies"
        run: |
          sudo apt-get install -y make git stow

      - name: "Run tests"
        env:
          TERM: "dumb"
        run: |
          make clean
          make install
